ServiceStack/ServiceStack.OrmLite

src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.Sqlite/SqliteOrmLiteDialectProviderBase.cs, tests/ServiceStack.OrmLite.Tests/OrmLiteUpdateTests.cs
Updating blobs was failing because the data was written converted to a base64
string and read as binary.
=> Make updating blobs work for Oracle and SQLite.

src/ServiceStack.OrmLite/Expressions/ReadExpressionCommandExtensions.cs, src/ServiceStack.OrmLite/OrmLiteReadCommandExtensions.cs, src/ServiceStack.OrmLite/OrmLiteReadExpressionsApi.cs, tests/ServiceStack.OrmLite.Tests/LoadReferencesTests.cs
Added additional optional string params to LoadSelect methods to allow for selective reference loading.
Example:
var dbCustomers = db.LoadSelect<Customer>(q => q.Id == customer.Id, "PrimaryAddress");
This is in response to [this UserVoice request](http://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/6656885-allow-loadselect-to-selectively-load-references)
=> Allow optional parameter list of reference field names to include in LoadSelect()

src/ServiceStack.OrmLite.Oracle/OracleNamingStrategy.cs
1. Schema name and table name should be separated by "." instead of "_".
2. Each portion of the identifier (eg schema name, table name, column name) should be a maximum of 30 bytes.
Source: http://docs.oracle.com/cd/B28359_01/server.111/b28286/sql_elements008.htm#SQLRF00223
=> Update GetTableName Function

src/ServiceStack.OrmLite/OrmLiteSchemaModifyApi.cs
Updated static DropForeignKey<T> method to use dialect provider's syntax from the model definition's GetDropForeignKeyConstraints string result instead of using fixed string. Also consolidated multiple dbConn.GetDialectProvider() calls into a single call.
Was getting an invalid syntax near FOREIGN when running this method against SQL Server because the syntax should be "ALTER TABLE [Table] DROP CONSTRAINT [FK];" yet this method had "ALTER TABLE [Table] DROP FOREIGN KEY [FK];".  (https://msdn.microsoft.com/en-us/library/ms189579.aspx).
=> Updated DropForeignKey<T> to use dialect provider

src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs, tests/ServiceStack.OrmLite.Tests/OrmLiteCreateTableTests.cs
Before this change the select would ignore the index because it forced Oracle to convert the key value to a string. Ouch.
=> Fix compact guid option in Oracle provider to do searches correctly

src/ServiceStack.OrmLite/Support/LoadList.cs, tests/ServiceStack.OrmLite.Tests/LoadReferencesJoinTests.cs
Added table names to generated join statement to address [issue 275](https://github.com/ServiceStack/Issues/issues/275)
Could you please have a review @mythz ?
=> LoadSelect fails with column name conflict on join

src/ServiceStack.OrmLite/OrmLiteResultsFilter.cs, tests/ServiceStack.OrmLite.Tests/CaptureSqlCommandFilterTests.cs, tests/ServiceStack.OrmLite.Tests/MockAllApiTests.cs, tests/ServiceStack.OrmLite.Tests/ServiceStack.OrmLite.Tests.csproj
OrmLiteResultsFilter now has a SqlCommandFilter action similar to
SqlFilter. This allows you to filter on the actual SqlCommand instead of
just the sql statement itself. This can be useful especially if you are
trying to troubleshoot the values that are being inserted as parameters.
I created a basic result filter similar to the existing CaptureSqlFilter
called CaptureSqlCommandFilter. This attempts to preserve the command data
as a new SqlCommandDetails object with parameter values stored in a
Dictionary along with the Sql string.
I created unit tests for the SqlCommandFilter similar to those for
SqlFilter and added similar checks for existing tests that use SqlFilter.
--
This is a product of me digging into OrmLite to discover why SqlGeography
types weren't being inserted into the …
=> Extended OrmLiteResultsFilter to filter on IDbCommand.

src/T4/OrmLite.Core.ttinclude
I have several Table Valued Functions in my project. Rather than create & manage POCO objects by hand to deal with the return types, I've updated the T4 template to create them. Similar to views, it is disabled by default and can be switched on via the IncludeFunctions boolean.
=> (MSSQL) Add support for Table Valued Functions

src/ServiceStack.OrmLite/Expressions/ParameterizedSqlExpression.cs, tests/ServiceStack.OrmLite.Tests/CaptureSqlFilterTests.cs, tests/ServiceStack.OrmLite.Tests/Expression/SqlExpressionTests.cs, tests/ServiceStack.OrmLite.Tests/OrmLiteExecFilterTests.cs
first commit is a small fix for the refactoring into ParameterizedSqlExpression
second commit contains fixes for some unit tests (mostly unrelated to parameterization) that were failing for oracle
=> fixes for oracle provider

src/ServiceStack.OrmLite.Sqlite/SqliteExpression.cs, src/ServiceStack.OrmLite/Expressions/Sql.cs, src/ServiceStack.OrmLite/Expressions/SqlExpression.cs, tests/ServiceStack.OrmLite.Tests/LoadReferencesTests.cs
Allows much more robust Select filtering.  Sub-expression must return a single column.
Can use like this:
var customersSubFilter = db.From<Customer>().Select(c => c.Id);
var orderQuery = db.From<Order>().Where(q => Sql.InExpression(q.CustomerId, customersSubFilter));
var dbOrders = db.Select(orderQuery);
To generate SQL like this:
SELECT * FROM Orders WHERE CustomerId IN (SELECT Id From Customers)
=> Added new static method Sql.InExpression to support sub-query SqlExpressions

src/ServiceStack.OrmLite.SqlServer/SqlServerOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.SqlServerTests/Issues/CustomSelectWithPagingIssue.cs, src/ServiceStack.OrmLite.SqlServerTests/ServiceStack.OrmLite.SqlServerTests.csproj
UseAliasesOrStripTablePrefixes function in SqlServerOrmLiteDialectProvider is not handling well custom selects with commas in it, eg ( SELECT DATEADD(d,1,GETDATE()) AS tommorow, CASE WHEN foo IN (1,2) THEN ...). It breaks the sql. 
Simple solution is to use all fields from subquery (with additional RowNum field last as last). That makes UseAliasesOrStripTablePrefixes obsolete.
=> issue with SqlServerDialectProvider CustomSelect with dots and commas and paging

src/ServiceStack.OrmLite.SqlServerSpatialsTest/Properties/AssemblyInfo.cs, src/ServiceStack.OrmLite.SqlServerSpatialsTest/ServiceStack.OrmLite.SqlServerTests.Spatials.csproj, src/ServiceStack.OrmLite.SqlServerSpatialsTest/SqlServerGeographyTypeConverter.cs, src/ServiceStack.OrmLite.SqlServerSpatialsTest/SqlServerGeometryTypeConverter.cs, src/ServiceStack.OrmLite.SqlServerSpatialsTest/SqlServerSpatialsOrmLiteTestBase.cs, src/ServiceStack.OrmLite.SqlServerSpatialsTest/SqlServerSpatialsTest.cs, src/ServiceStack.OrmLite.SqlServerSpatialsTest/app.config, src/ServiceStack.OrmLite.SqlServerSpatialsTest/packages.config, src/ServiceStack.OrmLite.sln, src/packages/repositories.config
Added new test project demonstrating the use of Spatials (both Geometry and Geography) types with OrmLite.  This functionality depends on the Microsoft.SqlServer.Types library from NuGet, plus references to the unmanaged libraries msvcr100.dll & SqlServerSpatials110.dll that are available from Microsoft's site (SQL Server version specific).
I attempted t0 figure out ways to integrate anything into OrmLite, but no approach was pretty. One thought I had about making this functionality more streamlined with OrmLite, was to wrap the Microsoft Libraries (new project) and provide interfaces that user's could inherit so that they don't have to mess with these over complicated libraries, then possibly provide some SqlExpressions for the type specific functions (i.e. STLength()), but this all …
=> Added test project demoing the use of Spatials

src/ServiceStack.OrmLite.SqlServerSpatialsTest/ServiceStack.OrmLite.SqlServerTests.Spatials.csproj, src/ServiceStack.OrmLite.SqlServerSpatialsTest/SqlServerGeographyTypeConverter.cs, src/ServiceStack.OrmLite.SqlServerSpatialsTest/SqlServerGeometryTypeConverter.cs, src/ServiceStack.OrmLite.SqlServerSpatialsTest/SqlServerSpatialsOrmLiteTestBase.cs, src/ServiceStack.OrmLite.SqlServerSpatialsTest/SqlServerTypeConverter.cs
Created new SqlServerTypeConverter abstract class for SQL Server Spatial Type Converters. Moved unmanaged library handling into new class' constructor. Provided optional parameters on converters for more developer flexibility with unmanaged filenames and path.
=> Created new SqlServerTypeConverter abstract class

src/ServiceStack.OrmLite.SqlServer.Converters/ServiceStack.OrmLite.SqlServer.Converters.csproj, src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerConverters.cs, src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerGeographyTypeConverter.cs, src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerGeometryTypeConverter.cs, src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerHierarchyIdTypeConverter.cs, src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerTypeConverter.cs, src/ServiceStack.OrmLite.SqlServerTests/Converters/ConvertersOrmLiteTestBase.cs, src/ServiceStack.OrmLite.SqlServerTests/Converters/HierarchyIdTests.cs, src/ServiceStack.OrmLite.SqlServerTests/Converters/SpatialsTests.cs, src/ServiceStack.OrmLite.SqlServerTests/ServiceStack.OrmLite.SqlServerTests.csproj, src/packages/repositories.config
Added support for the HierarchyId data type to the *SqlServer.Converters* project, included some support for converting to and from NULL values for all 3 *SqlServer.Converters*, and organized/updated the related testing.
Lastly, I have enabled the NuGet package restore option on the project.
=> Added support for the HierarchyId data type to the SqlServer.Converters package

src/ServiceStack.OrmLite.SqlServer/Converters/SqlServerDateTime2Converter.cs, src/ServiceStack.OrmLite.SqlServerTests/Datetime2Tests.cs
datetime2 can hold up to 7 fractional seconds
add SqlServerDateTime2Converter.ToQuotedString override that includes 7 fractional seconds in format
update unit test to test select on datetime2 value that has 7 fractional seconds
=> fix handling of sqlserver datetime2 fractional second precision

src/T4/OrmLite.Core.ttinclude, src/T4/OrmLite.SP.tt
Use SQL metadata to build result classes if SPs have output columns. 
I added a global flag IncludeSPReturnTypes (default is false) to control the behavior.
=> Added support to generate result type classes for SPs.

src/ServiceStack.OrmLite/OrmLiteReadCommandExtensions.cs
previous order of setting value before type causes "Value does not fall within the expected range"
in oracle, on types like .NET boolean which has no direct corresponding type in the database
=> fix order of setting DbType and Value when creating DbDataParameter

src/ServiceStack.OrmLite/Converters/SpecialConverters.cs
I removed the ToString() on an enum so the serialization of it can be
done by the configured StringSerializer.
Because some Expression related stuff changed when building with VS2015
Update 1 this resulted in an issue when I wanted my StringSerializer to
behave differently when serializing enums.
See:
http://stackoverflow.com/questions/34099809/expressions-breaking-code-when-compiled-using-vs2015-update-1
=> Removed ToString so it uses StringSerializer

src/ServiceStack.OrmLite.MySql/Converters/MySqlDateTimeConverter.cs
BUG:mysql数据库中的字段为datetime类型时,读取出来的数据库值类型为mysqldatetime,强转为datetime时会抛出异常
=> MySql DateTime Column Read 2 donet Datetime type  throw error,

src/ServiceStack.OrmLite.Oracle.Tests/ServiceStack.OrmLite.Oracle.Tests.csproj, src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
@mythz Here is a fix for parameterized stuff for the Oracle provider. It cuts the failing tests from 37 to 21, and it makes your new parameterized updates work. BTW, thanks very much for that - we really wanted that. Cheers, Bruce
=> Fix CreateParameter in Oracle provider and add missing DefaultValueTests

src/T4/OrmLite.Poco.tt
Had incorrect property name in template. Corrected to intended name.
=> Correct typo in new CreateAutoQueryTypes feature of T4 template

src/ServiceStack.OrmLite.Oracle/Converters/OracleDateTimeOffsetConverter.cs, src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.Oracle/OracleTimestampConverter.cs, src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
@mythz Here are a couple more fixes for the Oracle provider. It now only fails on the tests that it has always failed on.
It also supports the Oracle fully-managed provider (but defaults to the old one), except for a problem with initialization which I haven't figured out - when it attempts to load the managed provider a callback into OrmLite occurs for some reason which I don't understand and things go very sideways from there because it starts executing code which should not be run at that point in time, If you comment out the oracle.manageddataaccess section in machine.config then it all works. Cheers, Bruce
=> Fix time stamp types

src/ServiceStack.OrmLite.Oracle.Tests/ServiceStack.OrmLite.Oracle.Tests.csproj, tests/ServiceStack.OrmLite.Tests/ConverterTests.cs
@mythz We had a problem with bools in SQLite in 4.0.48, so I was checking that it was OK in 4.0.52. When doing so, I noticed that the update in the converter test was not doing what it really wanted to do because  the keys were off by 1. Hence this fix.
=> ConverterTests did update wrong so fix it, also add it to Oracle tests

src/T4/OrmLite.SP.tt
Adding another rename condition to deal with Stored Procedure outputs which are not valid C# property names.
=> Rename invalid property names including % sign ot valid output

src/ServiceStack.OrmLite/OrmLiteConfigExtensions.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs, src/ServiceStack.OrmLite/OrmLiteEnumAsIntAttribute.cs, src/ServiceStack.OrmLite/ServiceStack.OrmLite.csproj, src/ServiceStack.OrmLiteV45/ServiceStack.OrmLiteV45.csproj
Add functionality to allow enums to be stored as integer values without having to declare them as "flags"
1. Create new attribute type EnumAsAttrubute. This works just as a property label - the class has no functionality.
2. In OrmLiteConfigExtensions.cs - GetModelDefinition(), Check for this new attribute, and if included, set treatAsType to the underlying type.
3. In OrmLiteDialectProviderBase.cs - GetConverterBestMatch(), use fieldDef.ColumnType rather than fieldDef.FieldType. ColumnType will return FieldType anyway if TreatAsType is null.
=> add functionality to allow enums to be stored as integer values

src/ServiceStack.OrmLite.SqlServerTests/Expressions/AuthorUseCase.cs, src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
Sql.In(empty array) and Sql.In(null) are now evaluated as false (i.e. match no rows) rather than failing with an unhelpful error like "System.Data.SqlClient.SqlException : Incorrect syntax near ')'." or NullReferenceException, respectively.
=> Fixed handling of Sql.In(empty array) and Sql.In(null)

tests/ServiceStack.OrmLite.Tests/OrmLiteQueryTests.cs
@mythz The added test, Can_query_column_as_nullable demonstrates a stack overflow in a query. I suppose you can argue that it should be illegal to call a column nullable when it isn't nullable in the database, but this code works with 4.0.48 and earlier.
=> Demonstrate stack overflow in query.

src/ServiceStack.OrmLite.Oracle/Converters/OracleStringConverters.cs
@mythz This fixes the mysterious failures I was getting. Something changed so that the length is copied into the parameter as the max size, so it needs to be correct now.
Shortly I'll be able to get back to the memory leak issue.
=> Fix the Oracle string length default in the string converter

src/ServiceStack.OrmLite.MySql.Tests/EnumTests.cs, src/ServiceStack.OrmLite/OrmLiteWriteCommandExtensions.cs
Hey @mythz,
Related to [issue posted in the forums](https://forums.servicestack.net/t/enumasint-field-not-loading-when-nullable-4-0-54/2170), I found a simple solution to show way forward/issue with nullable enum properties casting from integer.
Better solution would probably be done in the Express building in `PropertyInvoker.cs` 
https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/ServiceStack.OrmLite/PropertyInvoker.cs#L37
Expression could build a predicate checking for Enum + Nullable type, eg 
```
Nullable.GetUnderlyingType(propertyInfo.PropertyType) != null
&& Nullable.GetUnderlyingType(propertyInfo.PropertyType).IsEnum)
``` 
Not familiar with Expression building, so was unsure how to build an expression to call equivalent of:
```
var enumType = …
```
=> MySQL issue with nullable enum + int casting prob

tests/ServiceStack.OrmLite.Tests/ConverterTests.cs
Here is a unit test that reproduces the problem. I'm not sure what it _should_ do, but definitely not _that_. :) In v4.0.44 it returned null, which isn't great either, as it masks the problem (lack of a converter). A helpful exception would probably be good here, but I don't know the best place to throw it.
=> StackOverflowException when FromDbValue() is called with a value type that has no converter registered

src/ServiceStack.OrmLite/Expressions/WriteExpressionCommandExtensions.cs, src/ServiceStack.OrmLite/IOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs, src/ServiceStack.OrmLite/OrmLiteWriteExpressionsApi.cs, tests/ServiceStack.OrmLite.Tests/ApiSqlServerTests.cs, tests/ServiceStack.OrmLite.Tests/ApiSqliteTests.cs
Implement an UpdateIncrement API similar to UpdateOnly, but that generates SQL to add the value to the existing database field instead of doing attribution, when the field is a numeric field. Other field types still do attribution and we can mix field types.
db.UpdateIncrement(new Person { Age = 5 }, db.From<Person>().Update(p =>p.Age).Where(x => x.FirstName == "Jimi"));
will generate this SQL:
UPDATE "Person" SET "Age" = "Age" + 5 WHERE ("FirstName" = 'Jimi')
This is usefull to increment counter, totals, etc. without having to load the object from the BD first and avoinding concurrency conflicts.
=> Implemented an UpdateIncrement API

src/T4/OrmLite.Core.ttinclude, src/T4/OrmLite.Poco.tt
Hit a problem during development where we'd have an item described below:
```
Item {
OwnerId: 1,
Owner2Id: 2
}
```
Added the following properties to the partial class to load references:
```
[Reference]
public Owner Owner { get; set; }
[Reference]
public Owner Owner2 { get; set; }
```
However, on doing a Db.LoadSingleById(), we'd end up with this:
```
Item {
OwnerId: 1,
Owner: { Id: 1, Name: "Owner" },
Owner2Id: 2,
Owner2: { Id: 1, Name: "Owner" }
}
```
The first Owner entity was being loaded into the second.
Adding the [References(typeof(Owner))] attribute to the foreign key field in the POCO generated by the T4 templates resolved the odd behaviour, and brought the POCO's more in line with the code demonstrated on the Ormlite documentation page.
The result is that in the POCO, this:
``` …
```
=> Enhance T4 templates for SqlServer to include more foreign key support

src/ServiceStack.OrmLite.SqlServerTests/SchemaTests.cs, src/ServiceStack.OrmLite.SqlServerTests/ServiceStack.OrmLite.SqlServerTests.csproj
OrmLiteSchemaModifyApi.DropColumn() fails when used with SQL Server, because the syntax it uses is `ALTER TABLE table_name DROP column_name` while SQL Server expects `ALTER TABLE table_name DROP COLUMN column_name` This unit test reproduces the problem. It fails with
```
System.Data.SqlClient.SqlException : 'Name' is not a constraint.
Could not drop constraint. See previous errors.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet …
```
=> DropColumn fails in SQL Server

src/ServiceStack.OrmLite.PostgreSQL.Tests/CreatePostgreSQLTablesTests.cs, src/ServiceStack.OrmLite.PostgreSQL.Tests/SchemaTests.cs, src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerGeographyTypeConverter.cs, src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerGeometryTypeConverter.cs, src/ServiceStack.OrmLite.SqlServerTests/SchemaTests.cs, src/T4/OrmLite.Core.ttinclude, tests/ServiceStack.OrmLite.Tests/LoadReferencesJoinTests.cs, tests/ServiceStack.OrmLiteV45.Tests/LoadReferenceJoinTests.cs, tests/ServiceStack.OrmLiteV45.Tests/T4/OrmLite.Core.ttinclude
Some fixes to unit tests that failed for me, especially due a case-sensitive server collation for SQL Server.
PostgreSQL tests still fail due to the mismatch in Npgsql version (2.2.7 vs 3.0.5), which can be fixed by downgrading the test projects to Npgsql 2.2.7, but I'm not including that in this PR.
=> Unit test fixes

src/ServiceStack.OrmLite.PostgreSQL.Tests/OrmLiteInsertTests.cs, src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerHierarchyIdTypeConverter.cs
This fixes 2 more unit tests, similar to PR #506.
"hierarchyid" was case-sensitive just like "geometry" and "geography" and my SQL Server quotes the column name in `RETURNING "id"` (probably a server setting somewhere.
Now all tests in the Tests project pass and only 1 test in SqlServerTests fails: `Can_execute_stored_proceduce_returning_scalars` says with "Could not find stored procedure 'GetUserIdsFromEmailAddresses'."`
=> More unit test fixes

src/ServiceStack.OrmLite.SqlServerTests/Expressions/EqualityExpressionsTest.cs
Shows a current issue: when COALESCE is on the right side of a comparison, it's serialized **into** the query param as a string. So the test Can_select_equals_coalesce_on_the_right_expression() will always fail.
From what I see SqlExpression.VisitFilter runs ConvertToPlaceholderAndParameter(ref right). Which adds a param "@1" with the value "{COALESCE("NullableCol",@0)}", then sets right to "@1".
Not sure how to fix it reliably & elegantly... especially to treat nested expressions.
=> Add COALESCE binary expression tests

src/ServiceStack.OrmLite.Firebird/FirebirdOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.PostgreSQL/PostgreSQLDialectProvider.cs, src/ServiceStack.OrmLite/Expressions/SqlExpression.cs, src/ServiceStack.OrmLite/FieldDefinition.cs, src/ServiceStack.OrmLite/IOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs, tests/ServiceStack.OrmLite.Tests/Expression/SqlExpressionTests.cs
Added support for selecting all of a table's columns in SqlExpression via `.Select<TableA, TableB>((a, b) => new { a })`. If a property name is specified in the anonymous type it's used as a prefix for every column, e.g. `.Select<TableA, TableB>((a, b) => new { ThisIsA = a })` would prefix every column of TableA with "ThisIsA". Property names can also now be used as aliases for individual columns, e.g. `.Select<TableA, TableB>((a, b) => new { a, BName = b.Name })` would result in "SELECT ..., TableB.Name as BName".
I had to add a few extra classes (SelectList, etc.) and make a breaking change the return type of IOrmLiteDialectProvider.GetRowVersionColumnName() to be able to manipulate the column aliases without major hacks. Perhaps they can be useful elsewhere as well. This is technically …
=> Select entire table in SqlExpression.Select() using anonymous types

src/ServiceStack.OrmLite/Expressions/SqlExpression.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs, src/ServiceStack.OrmLite/OrmLiteUtils.cs, tests/ServiceStack.OrmLite.Tests/ApiSqlServerTests.cs, tests/ServiceStack.OrmLite.Tests/ApiSqliteTests.cs, tests/ServiceStack.OrmLite.Tests/Expression/SqlExpressionTests.cs, tests/ServiceStack.OrmLiteV45.Tests/ApiPostgreSqlTestsAsync.cs, tests/ServiceStack.OrmLiteV45.Tests/ApiSqlServerTestsAsync.cs, tests/ServiceStack.OrmLiteV45.Tests/ApiSqliteTestsAsync.cs
PR #514 caused `.GroupBy(x => new { ColumnAlias = x.ColumnName })` to fail, because it was translated to "GROUP BY ColumnName AS ColumnAlias", which is invalid SQL. Added a test for this and for `.GroupBy(x => new { x })` which groups by all columns
=> Fixed bug in .GroupBy() introduced in PR #514

src/ServiceStack.OrmLite/FieldDefinition.cs, src/ServiceStack.OrmLite/ModelDefinition.cs, src/ServiceStack.OrmLite/OrmLiteUtils.cs, tests/ServiceStack.OrmLite.Tests/Issues/ColumnGuessingTests.cs, tests/ServiceStack.OrmLite.Tests/ServiceStack.OrmLite.Tests.csproj
This resulted in a nasty production bug for us where data was being mapped to the wrong column (as well as the right column). It's highly unexpected behaviour from the user point of view. I really think column guessing should be disabled by default, but this patch at least avoids guessing for a column that was already matched exactly.
To make the `Does_populate_custom_mixed_columns` unit test pass again I had to fix ModelDefinition.GetFieldDefinition() to keep looking for a case-sensitive match even when a case-insensitive match is found, rather than relying on the guessing to fix this later.
Adding `FieldDefinition.ToString()` just makes debugging much easier - I hope this is OK.
=> Do not guess column mapping when an exact match is found for a requested column

src/ServiceStack.OrmLite.SqlServer/ServiceStack.OrmLite.SqlServer.csproj, src/ServiceStack.OrmLite.SqlServer/SqlServerExpression.cs, src/ServiceStack.OrmLite.SqlServer/SqlServerExpressionExtensions.cs, src/ServiceStack.OrmLite.SqlServer/SqlServerTableHint.cs, src/ServiceStack.OrmLite.SqlServerTests/ServiceStack.OrmLite.SqlServerTests.csproj, src/ServiceStack.OrmLite.SqlServerTests/UseCase/JoinWithHintUseCase.cs, src/ServiceStack.OrmLite/Expressions/SqlExpression.Join.cs
It looked like extension methods were the easiest way to implement this. Table hints vary by provider (if any), and putting them on to the base SqlExpression<T> seemed wrong. Open to any suggestions!
=> Added table hints to Sql Server join expressions

src/ServiceStack.OrmLite/OrmLiteResultsFilterExtensions.cs
The async equivalents are already public: https://github.com/ServiceStack/ServiceStack.OrmLite/blob/b8b26326ce46ac04191eedba4589d59fd4afaafd/src/ServiceStack.OrmLite/Async/OrmLiteResultsFilterExtensionsAsync.cs#L16
=> Make all ExecNonQuery overloads public

tests/ServiceStack.OrmLite.Tests/OrmLiteInsertTests.cs
Hi @mythz,
We run the Oracle tests periodically. There are a few that currently fail. We are in the process of addressing some of the causes of these failures, e.g. #527. However there are some failing tests which will never work on Oracle. We would prefer to just ignore these. Please let me know if that's any kind of problem.
FYI @BruceCowan-AI
=> Skip InsertOnly tests for Oracle

src/ServiceStack.OrmLite/OrmLiteReadApi.cs, src/ServiceStack.OrmLite/OrmLiteResultsFilterExtensions.cs, tests/ServiceStack.OrmLite.Tests/OrmLiteExecuteNonQueryTests.cs
This provides an alternative to SqlProc for executing non-query stored procedure with output params. This way uses a callback rather than returning a dbCmd (like SqlProc). It can be used the same way SqlList is for queries.
=> Add ExecNonQuery overload with dbCmdCallback

src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
OracleOrmLiteDialectProvider.ToCreateTableStatement() now skips fields with CustomSelect attribute.
@mythz - Right now, the test `Can_select_custom_field_expressions()` in CustomSqlTests fails on Oracle. The change in this PR causes it to pass.
=> Handle fields with CustomSelect attribute in Oracle provider

src/ServiceStack.OrmLite/Async/OrmLiteReadCommandExtensionsAsync.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs, src/ServiceStack.OrmLite/OrmLiteReadCommandExtensions.cs
I've removed the reset of CommandTimeout where it would be set by the CreateCommand in the ExecFilter.
https://forums.servicestack.net/t/setcommandtimeout/3063/4
=> don't need to reset CommandTimeout where it's already set in CreateCommand

src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerGeographyTypeConverter.cs, src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerGeometryTypeConverter.cs, src/ServiceStack.OrmLite.SqlServer.Converters/SqlServerHierarchyIdTypeConverter.cs, src/ServiceStack.OrmLite.SqlServer/SqlServer2012OrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.SqlServer/SqlServer2016OrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.SqlServerTests/Converters/SpatialsTests.cs
Fixed issue with the updating of SqlGeography types with SqlServer 2012 dialect provider. No longer needs a AppendCustomCondition override as converter handles this appropriately. Added unit test and cleaned up a few other small items.
=> Resolved continued issue #474

src/ServiceStack.OrmLite.SqlServer/SqlServer2012OrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.SqlServerTests/Converters/ConvertersOrmLiteTestBase.cs, src/ServiceStack.OrmLite.SqlServerTests/Expressions/ExpressionsTestBase.cs, src/ServiceStack.OrmLite.SqlServerTests/Issues/DeleteWithGeoTypesIssue.cs, src/ServiceStack.OrmLite.SqlServerTests/OrmLiteTestBase.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs
1. Fixed previously existing issue in construction of Update command where AppendFieldCondition was being called instead of Field = Parameter. (line 767 in OrmLiteDialectProviderBase.cs)
2. Added a new virtual AppendNullFieldCondition method to OrmLiteDialectProviderBase.cs to handle Spatial null conditions (uses a boolean property and not the IS NULL syntax).
3. Added AppendFieldCondition and AppendNullFieldCondition overrides to SqlServer2012OrmLiteDialectProvider.
4. Made dialect provider an optional parameter in the OpenDbConnection method on the SqlServerTests.
=> Fixed regression caused by last commit and fixed root issue.

NuGet.Core/ServiceStack.OrmLite.PostgreSQL.Core/ServiceStack.OrmLite.PostgreSQL.Core.nuspec
Feel free to ignore PR if incorrect (still find my way around .NET Core).
When trying to use the `ServiceStack.OrmLite.PostgreSQL.Core` package, it fails at runtime due to not being able to find `Npgsql 3.1.8`. This happens for both local Windows dev and running on linux.
If I add the `Npgsql 3.1.8` specifically, it works fine. Possibly cause it's depending on wrong version in nuspec? 
https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/ServiceStack.OrmLite.PostgreSQL/project.json#L20
Or is there another way to get the downstream dependencies to be added to the `project.json`? (this could just be a tooling issue as well I guess).
=> Update to 3.1.8 as fails to find DLL at runtime.

src/ServiceStack.OrmLite.Oracle.Tests/ServiceStack.OrmLite.Oracle.Tests.csproj, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs, tests/ServiceStack.OrmLite.Tests/DefaultValueTests.cs
@mythz Here is a simple little fix to `ToUpdateStatement` and `ToInsertStatement` which fail when one field in the poco has a name which is a leading subset of another field. I ran into it with my update changes. I think it is safe enough as field names should not contain special regular expression characters. Cheers, Bruce
=> Fix ToUpdateStatement and ToInsertStatement with subset named columns

src/ServiceStack.OrmLite.MySql/MySqlDialectProvider.cs, src/ServiceStack.OrmLite.PostgreSQL/PostgreSQLDialectProvider.cs, src/ServiceStack.OrmLite.SqlServer/SqlServerOrmLiteDialectProvider.cs
Fix the default value of the "token" parameter in Async methods of classes derived from OrmLiteDialectProviderBase to match those in the base class. Without this calling the methods via an instance of the derived class requires specifying a CancellationToken.
=> Fix the default value of the "token" parameter in Async methods

src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
Use GetQuotedColumnName instead of DialectProvider.GetQuotedColumnName inside SqlExpression.
Method GetQuotedColumnName in SqlExpression is virtual. Therefore this refactoring will add additional features for SqlExpression inheritors.
=> Use GetQuotedColumnName instead of DialectProvider.GetQuotedColumnName inside SqlExpression

tests/ServiceStack.OrmLite.Tests/CustomSqlExpressionTests.cs
I've added unit tests for my previous commits:
Using GetQuotedColumnName instead of DialectProvider.GetQuotedColumnName inside SqlExpression:
https://github.com/ServiceStack/ServiceStack.OrmLite/pull/566
https://github.com/ServiceStack/ServiceStack.OrmLite/pull/569
=> Unit tests for using GetQuotedColumnName instead of DialectProvider.GetQuotedColumnName inside SqlExpression

NuGet.Core/ServiceStack.OrmLite.PostgreSQL.Core/ServiceStack.OrmLite.PostgreSQL.Core.nuspec
Fix nuspec for Postgres Core as currently 1.0.39 fails to build as it's unable to find 3.2.2 reference.
=> Update nuspec for Postgres Core

src/T4/OrmLite.Poco.tt
Fixed an issue where the reference attribute would ignore the class prefix and suffix, causing a 'Cannot resolve symbol' error when IncludeReferences is true.
=> Fixed class name in reference attribute

src/ServiceStack.OrmLite/OrmLiteUtils.cs
The current method of checking leads to too many false positives, also having it iterate over each key + do additional operations to prevent this is possibly performs worse than a regex (this would need to be checked properly ofc).
=> SqlVerifyFragment improvement.

src/ServiceStack.OrmLite/IOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderExtensions.cs
This is to support being able to use ormlite in an application querying both sql server and oracle databases where the Oracle data provider is Devart.
Currently to use OrmLite with Devart, we need to set:
``
OrmLiteConfig.ParamNameFilter = paramName => $":{paramName}"
``
But because OrmLiteConfig is static, this breaks a separate Sql Server connection running in the same application.
This change would allow the ParamNameFilter to be overwritten for a specific dialect provider, if required.
=> Changed the ParamNameFilter to a instance variable on the Dialect Provider

src/ServiceStack.OrmLite.SqlServer/SqlServerOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.SqlServerTests/TypedExtensionTests.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs
My team at the company I work for are in the process of migrating from one DBMS to another. In this situation we can't set the global dialect provider as it causes syntax errors across the DBMSs.
This pull request fixes the issue for us for SQL Server, unless there is something we are doing wrong?
When attempting to use ORMLite extensions against and OrmLiteConnection an ArgumentNullException was thrown when calling to SqlFmt as the global provider was not set.
Using SqlFmt overload that accepts the current dialect provider stops the ArgumentNullException.
=> Allow ORMLite Extensions to be used without global dialect provider.

src/ServiceStack.OrmLite.SqlServer.Converters/ServiceStack.OrmLite.SqlServer.Converters.csproj, src/ServiceStack.OrmLite.SqlServer/SqlServer2016Expression.cs, src/ServiceStack.OrmLite.SqlServer/SqlServer2016OrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.SqlServer/SqlServer2017OrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.SqlServer/SqlServerDialect.cs, src/ServiceStack.OrmLite.SqlServerTests/Expressions/JsonExpressionsTest.cs, src/ServiceStack.OrmLite.SqlServerTests/ServiceStack.OrmLite.SqlServerTests.csproj
Added a few of the JSON SQL methods to the SqlServer 2016 Dialect Provider so developers can parse and query JSON objects and arrays directly from SQL Server. This should be helpful for developers who dump raw JSON into a single string field (NVARCHAR) and still need the ability to query this data. 
For example, if a developer stores an entire address as JSON into a single field and need to only query those where State = "NY", this should make it easier and much more efficient.
Note that my NUnit test adapter has been malfunctioning and I wasn't able to execute the tests, so you may find a few errors. Sorry ;-(.
=> Added 3 JSON Sql methods to the SQLServer 2016 Dialect Provider

src/ServiceStack.OrmLite.SqlServer/Converters/SqlServerSpecialConverters.cs, src/ServiceStack.OrmLite.SqlServerTests/RowVersionTests.cs, src/ServiceStack.OrmLite/Async/OrmLiteWriteCommandExtensionsAsync.cs, src/ServiceStack.OrmLite/Converters/SpecialConverters.cs, src/ServiceStack.OrmLite/IOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite/OrmLiteConfigExtensions.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs, src/ServiceStack.OrmLite/OrmLiteWriteCommandExtensions.cs
Follow up to https://forums.servicestack.net/t/cant-use-ormlite-rowversion-and-dapper-custom-sql-in-same-project/4947/4 in which I proposed allowing byte[] properties as RowVersion trackers so that the Dapper functionality embedded in ServiceStack can be used with records containing RowVersions (ulong is inconsistent with Dapper mapping and so crashes when using the two in combination).
All tests implemented for this new functionality are in the RowVersionTests.cs file.
Broadly speaking, the RowVersionConverter has become aware of the tracking field type within the FromDbValue method so that it can decide whether to force a parse to ulong or byte[] , and the FromDbRowVersion method was subsequently made redundant and removed.
The solution builds, BUT i do not have access to the db types …
=> Feature/rowversion: make RowVersion logic cater for ulong and byte[] properties

src/T4/OrmLite.Core.ttinclude
Add proper encoding of TIME(n) SqlServer fields to TimeSpan in T4 templates (still requires SqlServerTimeConverter to operate correctly)
Apply automatic substitution of valid SqlServer tables characters to valid .NET type name.
=> T4 mapping improvement for SqlServer 

src/ServiceStack.OrmLite/OrmLiteConfig.cs, src/ServiceStack.OrmLite/Support/LoadList.cs, src/ServiceStack.OrmLite/Support/LoadReferences.cs, tests/ServiceStack.OrmLite.Tests/SoftDeleteTests.cs
The primary use case the the enablement of developers to manipulate the Sql queries for loading references (seen a couple of questions online around it) one reference is :
https://forums.servicestack.net/t/code-to-traverse-all-object-graph-and-remove-issoftdeleted/5709
The current closest method is **OrmLiteConfig.SqlExpressionSelectFilter** in which you could filter out records that have been soft deleted for example
```
OrmLiteConfig.SqlExpressionSelectFilter = expression =>
{
if (expression.ModelDef.ModelType.HasInterface(typeof(IAuditedEntity)))
{
expression.Where<IAuditedEntity>(e => e.IsDeleted == false || e.IsDeleted == null);
}
};
```
this however unfortunately doesnt work the same for loading references, which only runs the above code for the SelectExpression component (missing …
=> Addition of a Filter to ORMConfig to enable users access to the Ref Sql Statement

src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
I have stackoverflow here:
https://stackoverflow.com/questions/56392375/servicestack-ormlite-oracle-cant-insert-object-with-sequence-attribute
After debug I see a bug when execute function GetNextValue(IDbCommand dbCmd, string sequence, object value), CommandText of IDbCommand has change from "insert into..." to "select seq.nextval.."
=> Fix bug can't insert data with sequence

tests/ServiceStack.OrmLite.Tests/AutoIdTests.cs
Guid.Empty is cleaner than new Guid().
=> Fix Guid.Empty instead of new Guid()

src/ServiceStack.OrmLite/OrmLiteReadCommandExtensions.cs, tests/ServiceStack.OrmLite.Tests/SelectParamTests.cs
Hi!
I cleaned my fork and created the new PR with only the commits containing the changes.
=> Clean PR: Create parameter with DBNull.Value for null values in OrmLiteReadCommand

tests/ServiceStack.OrmLite.Tests/OrmLiteConfigExtensionsTests.cs
I got performance problem after update OrmLite to version 5.7.0. I found the method that now works longer: ``OrmLiteConfigExtensions.GetModelDefinition``. I suppose the problem is in ``HasAttributeCached`` method that used in ``GetModelDefinition``. Also I changed ``HasAttribute`` to ``HasAttributeCached`` in my project and it also got slower.
I created two tests where you can see 5 times performance drop.
Could you fix this performance problem? I think it is very important not only for me.
=> HasAttributeCached perfomance issue

src/ServiceStack.OrmLite/Async/ReadExpressionCommandExtensionsAsync.cs, src/ServiceStack.OrmLite/Expressions/ReadExpressionCommandExtensions.cs, tests/ServiceStack.OrmLite.Tests/UseCase/SoftDeleteUseCase.cs
`countExpr` is a clone of `expression` so it did not gain any new parameters added by `.ToSelectStatement()`, which was causing an exception when being executed.
=> Fix RowCount not working with SelectFilters.

src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
remove `OracleConfiguration.TraceLevel=7` from `OracleOrmLiteDialectProvider.cs`
I don't think this option is suitable for all situations and will cause potential additional risks (this is also the motivation for modification after the problems I encountered in the actual project)
This option generates a large number of logs in the netcore environment, resulting in insufficient server disk space. As shown：
PS:
For scenarios that are really needed, users should decide for themselves or at least allow external configuration (such as providing options in OrmliteConfig)
=> Cancel Odp.Net's trace option setting from "OracleOrmLiteDialectProvider.cs"

src/ServiceStack.OrmLite.SqlServer.Data/ServiceStack.OrmLite.SqlServer.Data.Core.csproj, src/ServiceStack.OrmLite.SqlServer.Data/ServiceStack.OrmLite.SqlServer.Data.csproj
See twitter discussion https://twitter.com/danielmarbach/status/1224952168563838976
When referencing ServiceStack.OrmLite.SqlServer.Data to get access to Microsoft.Data.SqlClient the full framework target does not properly resolve the dependencies, It only ships netstandard2.0 but its dependencies have net45;netstandard2.0. This causes dependency issues. When you reference that package on net462 the package brings in netstandard but the dependencies go for net45 assemblies which then causes build errors like the following
It was then recommended to use ServiceStack.OrmLite.SqlServer.Data.Core which is netstandard only. Unfortunately if I pull this in I'm not able to set
```
OrmLiteConfig.DialectProvider = SqlServerDialect.Provider;
```
With a custom build containing the PR I can now …
=> Include appropriate files in ServiceStack.ormLite.SqlServer.Data.Core

src/ServiceStack.OrmLite/Expressions/SqlExpression.Join.cs, tests/ServiceStack.OrmLite.Tests/RowVersionTests.cs
When I was attempting to select from an InnerJoin db query of two table classes with `RowVersion` properties and a `Schema` attributes, I started receiving an exception.
I'm not sure if this error was introduced with the reworkings of RowVersion that have been done in the last week or perhaps the use-case has not been encountered before but it would appear that the schema for the table was not being appended when selecting the RowVersion column.
=> BUGFIX: Add schema prefix to inner join when present

src/ServiceStack.OrmLite.MySql/MySqlExpression.cs, tests/ServiceStack.OrmLite.MySql.Tests/DateTimeColumnTest.cs
currently, ```ToString``` on ```DateTime``` will ignore any format parameters and always convert to ```cast({quotedColName} as char(1000))```,but most developers (at least in our opinion) want to convert according to the specified format and use it in ```Where``` or ```Select```.
this commit achieves this goal by passing the ```ToString``` parameter as it is to the ```DateFormat``` function of Mysql.
=> add ToString format paramater support for MySql DateTime

src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs, tests/ServiceStack.OrmLite.Tests/Shared/Person.cs, tests/ServiceStack.OrmLite.Tests/ToInsertAndUpdateStatementTests.cs
Fix for when table class has reference type (treated as TEXT or JSON column) and is provided null. Previously generated `{}` for null values with if inserted and then retrieved results in different instance values.
Added 2 tests.
=> To insert statement dbnull check

src/ServiceStack.OrmLite.Firebird/FirebirdOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite.SqlServer/SqlServerOrmLiteDialectProvider.cs, src/ServiceStack.OrmLite/Async/WriteExpressionCommandExtensionsAsync.cs, src/ServiceStack.OrmLite/Expressions/WriteExpressionCommandExtensions.cs, src/ServiceStack.OrmLite/Legacy/WriteExpressionCommandExtensionsAsyncLegacy.cs, src/ServiceStack.OrmLite/Legacy/WriteExpressionCommandExtensionsLegacy.cs, src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs, tests/ServiceStack.OrmLite.SqlServer.Tests/Issues/StringLengthParamTests.cs
``InsertOnly`` had different logic than the ``Insert`` method when handling parameter values. Now ``InsertOnly`` also uses ``dialectProvider.SetParameterValues``.
=> Fix in InsertOnly for param greater than default length

src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
In multi thread environment, run AutoQuery.CreateQuery method with the same From Type will cause null reference.
=> Fix NullRefrenceException.

src/ServiceStack.OrmLite/Expressions/SqlExpression.Join.cs
When using ``CustomJoin`` to build complex queries, ``SqlExpression<T>`` will lose the ``Entity`` information it depends on in SQL.
example:
```C#
public class Result {
public string From{get;set;}
}
public class AssetInfo
{
public string DeviceId { get; set; }
}
public class Region
{
public string Code { get; set; }
}
```
And
```C#
var q=db.From<Result>()
.LeftJoin<AssetInfo>((x,y)=>x.From==y.DeviceId)
.CustomJoin("LEFT JOIN `Region` ON `AssetInfo`.`DeviceId` LIKE CONCAT(`Region`.`Code`,'%')")
.Where<Result,Region>((x,y)=>y.Code.StartsWith("some_code"));
q.ToMergedParamsSelectStatement(); 
```
The code will throw an exception in  ``SqlExpression.cs``.``private object EvaluateExpression(Expression m)``.
The reason is trying to calculate the result of the expression here, but the …
=> Enhance CustomJoin
