- src/ServiceStack.OrmLite.Oracle.Tests/OracleParamTests.cs
- src/ServiceStack.OrmLite.Oracle.Tests/ServiceStack.OrmLite.Oracle.Tests.csproj
- src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
- tests/ServiceStack.OrmLite.Tests/DateTimeOffsetTests.cs
-Added more reserved words to Oracle reserved word list
-Updated unit tests for new reserved words
-Added DateTimeOffset (date time with timezone) support for oracle provider
-Added unit tests for querying timestamp values
> AddOracleReservedWordsAndSupportForDateTimeOffset

- README.md
> just a dot forgotten

- README.md
space instead dot 
sorry about dat :dancers:
> OrmLite.SqlServer correction

- src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
- tests/ServiceStack.OrmLite.Tests/Expression/EqualityExpressionsTest.cs
> fix handling of null variable when parameterized statement is enabled

- src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
- tests/ServiceStack.OrmLite.Tests/Expression/ComplexJoinTests.cs
fix composite index creation error for oracle provider
> fix test to use incremented ids instead of hardcoded ids

- src/ServiceStack.OrmLite.Oracle/Converters/OracleByteArrayConverter.cs
- src/ServiceStack.OrmLite.Oracle/Converters/OracleDateTimeOffsetConverter.cs
- src/ServiceStack.OrmLite.Oracle/Converters/OracleEnumConverter.cs
- src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
- src/ServiceStack.OrmLite/OrmLiteResultsFilterExtensions.cs
Hi Demis, here is the promised PR.
> Here are some fixes for the problems. Unfortunately, not complete.

- src/ServiceStack.OrmLite.Oracle.Tests/OracleParamTests.cs
- src/ServiceStack.OrmLite.Oracle/Converters/OracleEnumConverter.cs
- src/ServiceStack.OrmLite.Oracle/Converters/OracleIntegerConverters.cs
- src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
- src/ServiceStack.OrmLite/Expressions/ParameterizedSqlExpression.cs
- src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs
- tests/ServiceStack.OrmLite.Tests/Expression/EqualityExpressionsTest.cs
fixes to oracle dialect provider when parameterized statement is enabled, and a couple of converter fixes.
> Fixes for parameterized statements

- src/ServiceStack.OrmLite/OrmLiteReadApi.cs
- src/ServiceStack.OrmLite/OrmLiteReadCommandExtensions.cs
- tests/ServiceStack.OrmLite.Tests/LoadReferencesTests.cs
Add "include" support to LoadSingleById to selectively include references.  
http://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/8748277-allow-loadsinglebyid-to-selectively-load-reference
> Add include support to LoadSingleById

- src/T4/OrmLite.Core.ttinclude
improvements to SP output export after additional testing on real-life SPs.
> Improve SP output export, prevent hidden outputs from becoming properties, and prevent duplicate names.

- src/T4/OrmLite.Core.ttinclude
- src/T4/OrmLite.SP.tt
More practical fixes against "ugly" DB structure.
> Fix SP & Poco to output properties starting with digits correctly.

- src/T4/OrmLite.Core.ttinclude
- src/T4/OrmLite.Poco.tt
- src/T4/OrmLite.SP.tt
Some additional improvements as I throw more datasets against it to see how it busts.
> Further refinements on POCO and SP templates

- src/ServiceStack.OrmLite/OrmLiteReadApi.cs
- src/ServiceStack.OrmLite/OrmLiteReadApiAsync.cs
Exists is currently counting ALL records to determine if 1 exists.  
This patch will limit the search to a single record - to save some time.
> Optimizing Exists Api

- src/ServiceStack.OrmLite/OrmLiteReadApi.cs
- src/ServiceStack.OrmLite/OrmLiteReadApiAsync.cs
> Incorrect .ToSelectStatement

- src/ServiceStack.OrmLite/IOrmLiteDialectProvider.cs
- src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs
- src/ServiceStack.OrmLite/OrmLiteWriteCommandExtensions.cs
so add it to the provider interface.
@mythz This will allow me to use optimized read in the Oracle provider.
> Oracle needs to use a "GetOracleValues" method instead of "GetValues"

- src/ServiceStack.OrmLite.Oracle/Converters/OracleStringConverters.cs
- tests/ServiceStack.OrmLite.Tests/OrmLiteUpdateTests.cs
@mythz Yes, you fixed the problem. Since you did I don't have to debug tomorrow, so here is the fix for my problem - I hadn't tested UseUnicode true before. And I fixed one more test.
> Fix Oracle string converter and one test

- src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
- tests/ServiceStack.OrmLite.Tests/ExpressionVisitorTests.cs
The following now work:
* "Where(x => true)" or "false" or an expression that is evaluated to true or false at runtime (by CachedExpressionCompiler.Evaluate). Of course, this is pointless on its own, but can be useful when building a more complex expression with And(), Or(), etc.
* "Where(x => x.NullableColumn == null)" or an expression that is evaluated to null at runtime
* "Where(x => x.NullableColumn.HasValue = true)" or "false" or an expression evaluated to true/false at runtime
* ... same with the boolean/null expression on the left
> Handle expressions that evaluate to true/false/nulls in Where() expression

- src/ServiceStack.OrmLite.MySql.Tests/OrmLiteCreateTableWithNamingStrategyTests.cs
- src/ServiceStack.OrmLite.Oracle.Tests/ServiceStack.OrmLite.Oracle.Tests.csproj
- src/ServiceStack.OrmLite.PostgreSQL.Tests/Issues/JsonDataTypeTests.cs
- src/ServiceStack.OrmLite.PostgreSQL.Tests/OrmLiteCreateTableWithNamigStrategyTests.cs
- src/ServiceStack.OrmLite.PostgreSQL.Tests/OrmLiteDropTableWithNamingStrategyTests.cs
- src/ServiceStack.OrmLite.PostgreSQL.Tests/PostgreSqlArrayTests.cs
- src/ServiceStack.OrmLite.PostgreSQL.Tests/SchemaTests.cs
- src/ServiceStack.OrmLite.PostgreSQL/Converters/PostgreSqlArrayConverters.cs
- src/ServiceStack.OrmLite.PostgreSQL/PostgreSQLDialectProvider.cs
- tests/ServiceStack.OrmLite.FirebirdTests/OrmLiteCreateTableWithNamigStrategyTests.cs
- tests/ServiceStack.OrmLite.FirebirdTests/ServiceStack.OrmLite.FirebirdTests.csproj
- tests/ServiceStack.OrmLite.Tests/OrmLiteCreateTableWithNamingStrategyTest.cs
- tests/ServiceStack.OrmLite.Tests/OrmLiteDropTableWithNamingStrategyTests.cs
- tests/ServiceStack.OrmLite.Tests/ServiceStack.OrmLite.Tests.csproj
- tests/ServiceStack.OrmLite.Tests/TemporaryNamingStrategy.cs
A number of fixes to make all unit tests in the ServiceStack.OrmLite.PostreSQL.Tests project pass
> Postgres test fixes

- src/ServiceStack.OrmLite.SqlServerTests/Issues/PrecisionAndScaleTests.cs
- src/ServiceStack.OrmLite/OrmLiteReadCommandExtensions.cs
Fixes https://github.com/ServiceStack/Issues/issues/452
> Add optional parameters (scale, precision, size) to AddParam

- src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
- tests/ServiceStack.OrmLite.Tests/ExpressionVisitorTests.cs
I made method for determines whether the expression is the parameter. Method supports expressions with nested properties, e.g.:
```C#
x=>x.Property1.Name
```
> Extracted method for checking Expression for the parameter.

- src/ServiceStack.OrmLite.Sqlite/SqliteExpression.cs
- src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
A few minor changes to consolidate logic in SqlExpression.cs after the addition of the Concat logic (#a4be4b7).
Thanks @OlegNadymov! Nice addition.
> A few minor changes to consolidate SqlExpression.cs

- src/ServiceStack.OrmLite.Oracle.Tests/ServiceStack.OrmLite.Oracle.Tests.csproj
@mythz 
Adding missing tests to Oracle test project. All of these tests are currently passing on Oracle.
FYI - @BruceCowan-AI .
> Include missing tests in Oracle test project

- tests/ServiceStack.OrmLite.Tests/OrmLiteInsertTests.cs
For illustration purposes only - not to be merged.
Entity attributes don't appear to be accounted for.
> Add tests demonstrating problems with InsertOnly

- src/ServiceStack.OrmLite.Oracle.Tests/ServiceStack.OrmLite.Oracle.Tests.csproj
- src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
- src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs
@mythz - can you take a look please?
> Fix schema related methods in Oracle provider

- src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
- tests/ServiceStack.OrmLite.Tests/CustomSqlExpressionTests.cs
I have Added support for visiting of virtual bool properties in custom SqlExpression.
> Added support for visiting of virtual bool properties in custom SqlExpression

- src/ServiceStack.OrmLite.Oracle/OracleOrmLiteDialectProvider.cs
- src/ServiceStack.OrmLite.Oracle/Properties/AssemblyInfo.cs
- tests/ServiceStack.OrmLite.Tests/EnumTests.cs
- tests/ServiceStack.OrmLite.Tests/Expression/SqlExpressionTests.cs
- tests/ServiceStack.OrmLite.Tests/Issues/CustomTypeTests.cs
- tests/ServiceStack.OrmLite.Tests/Issues/UtcDateTimeIssueTests.cs
- tests/ServiceStack.OrmLite.Tests/LocalizationTests.cs
- tests/ServiceStack.OrmLite.Tests/OrmLiteSelectTests.cs
- tests/ServiceStack.OrmLite.Tests/ShippersExample.cs
- tests/ServiceStack.OrmLite.Tests/StringSerializerTests.cs
- tests/ServiceStack.OrmLite.Tests/TestHelpers.cs
- tests/ServiceStack.OrmLite.Tests/UseCase/SimpleUseCase.cs
@mythz Here is a small PR which fixes a bunch of tests on the Oracle provider. Mostly it changes the tests, not the provider. I verified that the changes don't break other providers by running the tests on SQL Server.
> Fix oracle provider testing somewhat

- src/ServiceStack.OrmLite.Oracle.Tests/ServiceStack.OrmLite.Oracle.Tests.csproj
- src/ServiceStack.OrmLite/Async/OrmLiteWriteCommandExtensionsAsync.cs
- src/ServiceStack.OrmLite/Async/WriteExpressionCommandExtensionsAsync.cs
- src/ServiceStack.OrmLite/Expressions/WriteExpressionCommandExtensions.cs
- src/ServiceStack.OrmLite/IOrmLiteDialectProvider.cs
- src/ServiceStack.OrmLite/Legacy/WriteExpressionCommandExtensionsAsyncLegacy.cs
- src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs
- src/ServiceStack.OrmLite/OrmLiteWriteApi.cs
- src/ServiceStack.OrmLite/OrmLiteWriteApiAsync.cs
- src/ServiceStack.OrmLite/OrmLiteWriteCommandExtensions.cs
- src/ServiceStack.OrmLite/OrmLiteWriteExpressionsApi.cs
- src/ServiceStack.OrmLite/OrmLiteWriteExpressionsApiAsync.cs
- tests/ServiceStack.OrmLite.Tests/Async/OrmLiteUpdateTestsAsync.cs
- tests/ServiceStack.OrmLite.Tests/DefaultValueTests.cs
- tests/ServiceStack.OrmLite.Tests/OrmLiteUpdateTests.cs
- tests/ServiceStack.OrmLite.Tests/ServiceStack.OrmLite.Tests.csproj
- tests/ServiceStack.OrmLite.Tests/Shared/DefaultValues.cs
- tests/ServiceStack.OrmLite.Tests/Shared/UpdateCommandFilter.cs
@mythz THIS IS NOT READY FOR MERGE, here for your comments only. I think this generic update callback is close to what you wanted, and the test I added to `DefaultValueTests` shows using it to insert a last updated date (once I fix the test to do the substitution into the sql correctly). Obviously it also needs more tests. Please comment at will.
Cheers, Bruce
> A start at implementing generic update callback

- src/ServiceStack.OrmLite.Sqlite/SqliteOrmLiteDialectProviderBase.cs
- src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs
Added virtual method GetSchemaName
Added override for sqlite implentation
Made these changes to account for cross database operations that use a period in the schema name.
> Update OrmLiteDialectProviderBase.cs, SqliteOrmLiteDialectProviderBase.cs

- src/ServiceStack.OrmLite.SqlServer/Converters/SqlServerJsonStringConverters.cs
- src/ServiceStack.OrmLite.SqlServer/SqlServer2016OrmLiteDialectProvider.cs
- src/ServiceStack.OrmLite.SqlServerTests/Converters/ConvertersOrmLiteTestBase.cs
- src/ServiceStack.OrmLite.SqlServerTests/Converters/SqlGeographyTests.cs
- src/ServiceStack.OrmLite.SqlServerTests/Converters/SqlGeometryTests.cs
- src/ServiceStack.OrmLite.SqlServerTests/Converters/SqlHierarchyIdTests.cs
- src/ServiceStack.OrmLite.SqlServerTests/Expressions/AuthorUseCase.cs
- src/ServiceStack.OrmLite.SqlServerTests/Expressions/JsonExpressionsTest.cs
- src/ServiceStack.OrmLite.SqlServerTests/ForeignKeyAttributeTests.cs
- src/ServiceStack.OrmLite.SqlServerTests/OrmLiteTestBase.cs
- src/ServiceStack.OrmLite.SqlServerTests/SchemaTests.cs
- src/ServiceStack.OrmLite.SqlServerTests/ServiceStack.OrmLite.SqlServerTests.csproj
- src/ServiceStack.OrmLite.SqlServerTests/SqlServerExpressionVisitorQueryTest.cs
- src/ServiceStack.OrmLite.SqlServerTests/TableOptionAttributes/MemoryOptimizedAttributeTests.cs
- src/ServiceStack.OrmLite.SqlServerTests/TableOptionAttributes/TableOptionsOrmLiteTestBase.cs
- src/ServiceStack.OrmLite.SqlServerTests/UseCase/SimpleUseCase.cs
- src/ServiceStack.OrmLite/Expressions/Sql.cs
Sorry for the delay on this effort Demis! Had some changes at the paying job and couldn't make it back around until now.
Anyhow, I have gone back through my code and made some changes to get the Unit Tests executing correctly.  I only have one failing case, and it's due to a conversion error (object must inherit IConvertible, not sure why yet), but it's for a scenario that few would probably use.
Take a look and let me know what you think.
Oh, one side note... I found out that I had to add a Microsoft.NET.Test.Sdk NuGet dependency (only to the testing project) so that Visual Studio 2017 can properly discover the NUnit test cases using the proper adapter.
> Update Unit Tests and made some changes around the SQL Server 2016 JSON functions

- src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
- tests/ServiceStack.OrmLite.Tests/CustomSqlExpressionTests.cs
1. ordering by constant
2. using constant as column access.
> Added possibilities for custom sql expression:

- src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
- tests/ServiceStack.OrmLite.Tests/CustomSqlExpressionTests.cs
1. Removed checking by string for using parameters
2. Using constant in select part
> Expanding possibilities for custom sql expressions

- src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
- tests/ServiceStack.OrmLite.Tests/ExpressionVisitorTests.cs
I have one question.
@mythz How can I import key "servicestack-sn.pfx" which protected with password ?
> Add support of SQL-generation for String.Compare

- src/ServiceStack.OrmLite/Dapper/DataTableHandler.cs
- src/ServiceStack.OrmLite/Dapper/SqlDataRecordListTVPParameter.cs
- src/ServiceStack.OrmLite/Dapper/SqlMapper.Async.cs
- src/ServiceStack.OrmLite/Dapper/SqlMapper.DapperRowMetaObject.cs
- src/ServiceStack.OrmLite/Dapper/SqlMapper.GridReader.cs
- src/ServiceStack.OrmLite/Dapper/SqlMapper.IDataReader.cs
- src/ServiceStack.OrmLite/Dapper/SqlMapper.TypeDeserializerCache.cs
- src/ServiceStack.OrmLite/Dapper/SqlMapper.cs
- src/ServiceStack.OrmLite/Dapper/TypeExtensions.cs
Updated to latest dapper release with namespace change to match ss original.
> Updating dapper to release 1.60.1

- src/ServiceStack.OrmLite/Async/OrmLiteUtilExtensionsAsync.cs
This PR fixes missing DbNull value treatment on async result.
As of 5.7 async methods returns "different" values without this.
> Fix db null values on async methods

- src/ServiceStack.OrmLite.PostgreSQL/PostgreSQLDialectProvider.cs
Added int[] alias to match Postgres alias. Also added missing boolean array types.
> Add NativeTypes int[] alias and bool[] boolean[]

- tests/ServiceStack.OrmLite.PostgreSQL.Tests/OrmLiteExecuteProcedureTests.cs
Fixes the test and removes the test [Ignore] attribute.
Also adds additional execute option, with and without [Alias("")] attribute.
> Fix test execute stored procedure w/ array args

- src/ServiceStack.OrmLite/Expressions/WriteExpressionCommandExtensions.cs
- src/ServiceStack.OrmLite/OrmLiteWriteApi.cs
- src/ServiceStack.OrmLite/OrmLiteWriteCommandExtensions.cs
- src/ServiceStack.OrmLite/OrmLiteWriteExpressionsApi.cs
Delete does not have a command filter like Update and Insert methods, would be cool to have also.
I'm not sure if those are the best places to call the filter
> Delete command filter

- src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
Just new method UnsafeGroupBy.
> UnsafeGroupBy

- src/ServiceStack.OrmLite/UntypedApi.cs
UntypedApi Asynchronous API concurrency problem
> Fix the 'EndExecuteNonQuery' asynchronous concurrent execution

- src/ServiceStack.OrmLite.PostgreSQL/Converters/PostgreSqlDateOnlyConverter.cs
- src/ServiceStack.OrmLite/Converters/DateOnlyConverter.cs
- src/ServiceStack.OrmLite/Converters/TimeOnlyConverter.cs
- tests/ServiceStack.OrmLite.Tests/Net6TypeTests.cs
Equivalent to #663, but the commits is clearer.
> Grammar downgrade support vs2019

- src/ServiceStack.OrmLite.MySql/MySqlDialectProviderBase.cs
- src/ServiceStack.OrmLite/FieldDefinition.cs
- src/ServiceStack.OrmLite/OrmLiteConfigExtensions.cs
- src/ServiceStack.OrmLite/OrmLiteDialectProviderBase.cs
- tests/ServiceStack.OrmLite.MySql.Tests/OrmLiteCreateTableTests.cs
> Support custom order of columns when creating table
